apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rrqbhzom8-java-quarkus
  janus-idp.io/tekton: rrqbhzom8-java-quarkus
  backstage.io/kubernetes-id: rrqbhzom8-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rrqbhzom8-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
